### ISSUE TITLE
Get ready for a release

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/animatplot-ng#1]
- [x] Finish renaming to animatplot-ng (but do provide animatplot for importing)
- [x] Merge pull requests
- [x] Fix FTBFS for Python 3.10
- [x] setup GHA (based on circleci)
- [x] black?

**Comment by QuLogic** [comment]
Note, there is an upcoming failure with Matplotlib 3.5.0b1: https://koschei.fedoraproject.org/build/11016052

**Comment by dschwoerer** [comment]
> If you pass a `frame_prefix` to `setup` instead of `clear_temp=False`, then those files will not be removed.

(should resolve the matplotlib issue)

**Comment by dschwoerer** [comment]
https://pypi.org/project/animatplot-ng/
